-- INDEX workspace isolation. Auth identities are owned by Supabase auth.users.
begin;
create table public.workspaces(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table public.workspace_members(workspace_id uuid not null references public.workspaces on delete cascade,user_id uuid not null references auth.users on delete cascade,role text not null check(role in ('owner','editor','viewer')),primary key(workspace_id,user_id));
create index workspace_members_user_idx on public.workspace_members(user_id);
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
create policy members_read_self on public.workspace_members for select to authenticated using(user_id=(select auth.uid()));
create policy workspace_read on public.workspaces for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=id and m.user_id=(select auth.uid())));
grant select on public.workspace_members,public.workspaces to authenticated;
-- Workspace provisioning and membership changes are deliberately administrator-only.
create table public.sites(
 id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,
 name text not null check(length(name) between 2 and 100),domain text not null,url text not null check(url ~ '^https?://'),tier int not null check(tier between 1 and 3),niche text not null,
 status text not null default 'Unavailable' check(status in ('Healthy','Attention','Critical','Unavailable')),primary_keyword text not null default '',
 screenshot_url text,favicon_url text,archived boolean not null default false,scores jsonb,rank numeric,position numeric,clicks bigint,impressions bigint,pages int,indexed int,growth numeric,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,domain),unique(id,workspace_id));
create index sites_workspace_tier_idx on public.sites(workspace_id,tier) where not archived;
create table public.site_metrics_daily(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,date date not null,clicks bigint not null default 0 check(clicks>=0),impressions bigint not null default 0 check(impressions>=0),avg_position numeric not null default 0,total_pages int not null default 0,indexed_pages int not null default 0,organic_users bigint,source text not null default 'manual' check(source in ('demo','gsc','ga4','manual')),foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade,unique(site_id,date,source));
create index site_metrics_workspace_date_idx on public.site_metrics_daily(workspace_id,date desc);
create table public.seo_scores(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,date date not null,technical_score numeric check(technical_score between 0 and 100),content_score numeric check(content_score between 0 and 100),index_score numeric check(index_score between 0 and 100),authority_score numeric check(authority_score between 0 and 100),performance_score numeric check(performance_score between 0 and 100),cwv_score numeric check(cwv_score between 0 and 100),total_score numeric generated always as(round(technical_score*.25+content_score*.20+index_score*.15+authority_score*.15+performance_score*.15+cwv_score*.10)) stored,foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade,unique(site_id,date));
create table public.keywords(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,keyword text not null,country text not null default 'ID',device text not null default 'desktop' check(device in ('desktop','mobile','tablet')),tracked boolean not null default true,position numeric,previous numeric,clicks bigint not null default 0,impressions bigint not null default 0,volume bigint,foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade,unique(id,workspace_id),unique(site_id,keyword,country,device));
create table public.keyword_rankings(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,keyword_id uuid not null,date date not null,position numeric,impressions bigint,clicks bigint,ctr numeric,foreign key(keyword_id,workspace_id) references public.keywords(id,workspace_id) on delete cascade,unique(keyword_id,date));
create table public.pages(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,url text not null,title text,canonical text,index_status text,status_code int,seo_score numeric,last_crawled_at timestamptz,foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade,unique(site_id,url));
create table public.backlinks(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,source_domain text not null,source_url text not null,target_url text not null,anchor text,first_seen timestamptz,last_seen timestamptz,follow boolean,status text,foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade);
create table public.crawl_runs(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,status text not null default 'queued',started_at timestamptz,finished_at timestamptz,foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade,unique(id,workspace_id));
create table public.crawl_issues(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,crawl_run_id uuid not null,severity text not null,url text,code text not null,message text not null,foreign key(crawl_run_id,workspace_id) references public.crawl_runs(id,workspace_id) on delete cascade);
create table public.screenshots(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,image_url text not null,captured_at timestamptz not null default now(),viewport jsonb not null,hash text not null,visual_change_score numeric,foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade);
create index screenshots_site_time_idx on public.screenshots(site_id,captured_at desc);
create table public.alerts(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,title text not null,message text not null,severity text not null check(severity in ('info','warning','critical','success')),created_at timestamptz not null default now(),status text not null default 'open' check(status in ('open','resolved')),foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade);
create table public.content_items(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,site_id uuid not null,topic text not null,keyword text,author text,publish_date timestamptz,url text,quality_score numeric,state text not null default 'Idea' check(state in ('Idea','Research','Draft','Review','Scheduled','Published','Needs Update','Failed')),foreign key(site_id,workspace_id) references public.sites(id,workspace_id) on delete cascade,unique(id,workspace_id));
create table public.publishing_jobs(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,content_id uuid not null,status text not null default 'queued',scheduled_at timestamptz,error text,foreign key(content_id,workspace_id) references public.content_items(id,workspace_id) on delete cascade);
-- Only non-secret integration metadata belongs in an exposed table. OAuth tokens must be stored in a secret vault.
create table public.integrations(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,provider text not null check(provider in ('gsc','ga4','r2','crux')),status text not null default 'disconnected',property_id text,last_synced_at timestamptz,unique(workspace_id,provider));
create table public.activity_logs(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces on delete cascade,actor_id uuid references auth.users,action text not null,resource_id text,created_at timestamptz not null default now());
do $$ declare t text; begin
 foreach t in array array['sites','site_metrics_daily','seo_scores','keywords','keyword_rankings','pages','backlinks','crawl_runs','crawl_issues','screenshots','alerts','content_items','publishing_jobs','integrations','activity_logs'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('create index %I on public.%I(workspace_id)',t||'_workspace_idx',t);
 execute format('create policy workspace_read on public.%I for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid())))',t,t);
 execute format('grant select on public.%I to authenticated',t);
 end loop;
 foreach t in array array['sites','keywords','content_items','alerts'] loop
 execute format('create policy editor_insert on public.%I for insert to authenticated with check(exists(select 1 from public.workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''editor'')))',t,t);
 execute format('create policy editor_update on public.%I for update to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''editor''))) with check(exists(select 1 from public.workspace_members m where m.workspace_id=%I.workspace_id and m.user_id=(select auth.uid()) and m.role in (''owner'',''editor'')))',t,t,t);
 execute format('grant insert,update on public.%I to authenticated',t);
 end loop;
end $$;
create function public.touch_updated_at() returns trigger language plpgsql security invoker set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;
revoke all on function public.touch_updated_at() from public;
create trigger sites_updated before update on public.sites for each row execute function public.touch_updated_at();
commit;
